"""Phase 5 (Documentation) as Mermaid UML + an SRS traceability matrix --
Milestone 2 of the full-SDLC roadmap. Extends directly off Milestone 1's
already-approved SRS.md/HLD.md, no new infra or external credentials needed.

Scope: ~/.claude/rules/45-uml-diagram-lifecycle.md defines 13 diagram types
for a pipeline whose primary data source is a real AST-based CallGraph
builder. Vishwakarma has no such static-analysis tool, so this module
deliberately generates only the 4 types genuinely derivable from SRS.md +
HLD.md text alone via an LLM call (class/component/sequence/usecase); the
other 9 (state, activity, deployment, object, composite-structure,
interaction-overview, communication, call-graph, package) are explicitly
deferred, not dropped -- each needs either real source code to analyze or
infrastructure context this tool doesn't model.

This module is also the first real production use of AgentCoordinator's
genuinely parallel process spawning (Milestone 1.5's SRS/HLD chains stayed
sequential since each stage's input IS the previous stage's output; these
LLM-path diagrams have no data dependency on each other). Note precisely
what that buys: agent_runtime.py's dispatcher thread is single-threaded and
services every spawned process's LLM call serially through one request
queue, so multiple processes give real OS-level isolation and correct
dependency modeling -- NOT concurrent LLM throughput. Do not claim or
measure a speedup from this.

Milestone 3 closes part of the Milestone 2 gap above: class/component/
sequence are attempted first via mcp-uml-diagram's real Python-AST-based
tool calls (engine/mcp_client.py) -- genuinely derived from actual source
code, not LLM-guessed from HLD prose -- before falling back to the LLM
persona path for any type that isn't AST-resolvable (usecase, always) or
where the AST call failed/returned degraded output (fail-open, same
discipline as engine/kg_routing.py's route_persona()).
"""

from __future__ import annotations

import re
from pathlib import Path

from vishwakarma.engine.agent_runtime import AgentCoordinator, RemoteLLM
from vishwakarma.engine.calling import OnEvent, noop_event
from vishwakarma.engine.generate import GenerationError
from vishwakarma.engine.reasoning_utils import strip_reasoning_trace
from vishwakarma.engine.sdlc import srs_path_for
from vishwakarma.llm_client import LLMClient
from vishwakarma.mcp_client import MCP_SERVERS, call_mcp_tools
from vishwakarma.router import Router

AST_DIAGRAM_TYPES = ("class", "component", "sequence")
"""Diagram types mcp-uml-diagram can derive from real Python AST analysis --
"usecase" has no AST equivalent (it's inherently requirements-derived from
the SRS, not source code) and always goes through the LLM persona path."""

DIAGRAM_FRONTMATTER = "<!-- Generated by pipeline -- do not edit manually -->\n\n"

TRACEABILITY_HEADING = "## Traceability Matrix"

_MERMAID_DIAGRAM_INSTRUCTION = (
    "Produce ONLY a single Mermaid diagram block (starting with ```mermaid and "
    "ending with ```), with no prose before or after the fence. Cap the diagram "
    "at 50 nodes -- if the real content would exceed that, show only the most "
    "important top-level nodes and add a comment line inside the diagram: "
    "'%% Truncated: showing top N nodes'."
)

DIAGRAM_PERSONAS: dict[str, str] = {
    "class": (
        "You produce a Mermaid classDiagram that is really a module/file-relationship "
        "diagram styled as a UML class diagram -- its boxes represent FILES/MODULES from "
        "the HLD's 'Files & Responsibilities' and 'Key Design Decisions' sections, not "
        "individual classes with methods (the HLD text you're given deliberately excludes "
        "code-level detail, so do not invent method signatures or fields that aren't in "
        "the source text -- relationships between files/modules only). "
        + _MERMAID_DIAGRAM_INSTRUCTION
    ),
    "component": (
        "You produce a Mermaid graph/flowchart diagram showing the system's components "
        "and how they connect, derived from the HLD's 'System Overview' and file list. "
        + _MERMAID_DIAGRAM_INSTRUCTION
    ),
    "sequence": (
        "You produce a Mermaid sequenceDiagram for the system's main use case, derived "
        "from the HLD's 'Data Flow' section. "
        + _MERMAID_DIAGRAM_INSTRUCTION
    ),
    "usecase": (
        "You produce a Mermaid diagram (flowchart styled as a use-case diagram, since "
        "Mermaid has no native usecaseDiagram type) showing each Functional Requirement "
        "from the SRS as an actor-goal pair. "
        + _MERMAID_DIAGRAM_INSTRUCTION
    ),
}

_TRACEABILITY_SYSTEM_PROMPT = (
    "You are producing a requirements traceability matrix for a personal coding "
    "project. Given the approved SRS (with FR-NNN/NFR-NNN entries) and a list of "
    "the actual generated source file paths, map each FR/NFR to the file(s) most "
    "responsible for implementing it. You are given ONLY file paths, not their "
    "contents -- infer responsibility from filenames and the SRS's own wording. "
    "Output ONLY a Markdown table with exactly these columns: "
    "| FR/NFR | Files |. One row per FR/NFR. No prose before or after the table."
)


def _persona_generate_diagram(remote_llm: RemoteLLM, diagram_type: str, srs: str, hld: str) -> str:
    """Spawned-agent persona that generates one Mermaid diagram."""
    messages = [
        {"role": "system", "content": DIAGRAM_PERSONAS[diagram_type]},
        {"role": "user", "content": f"SRS:\n{srs}\n\nHLD:\n{hld}"},
    ]
    raw = remote_llm.call_role(
        "fallback_long_context", f"generate {diagram_type} diagram (Phase 5)", messages,
        light_reasoning=True, temperature=0.2, max_tokens=1200,
    )
    return strip_reasoning_trace(raw)


def _persona_generate_traceability(remote_llm: RemoteLLM, srs: str, file_list: list[str]) -> str:
    """Spawned-agent persona that maps FR/NFR entries to generated file paths."""
    user_content = f"SRS:\n{srs}\n\nGenerated file paths:\n" + "\n".join(file_list)
    messages = [
        {"role": "system", "content": _TRACEABILITY_SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]
    raw = remote_llm.call_role(
        "fallback_long_context", "generate traceability matrix (Phase 5)", messages,
        light_reasoning=True, temperature=0.0, max_tokens=800,
    )
    return strip_reasoning_trace(raw)


def _has_mermaid_fence(text: str) -> bool:
    """Return whether text actually contains a ```mermaid ... ``` block.

    The persona prompt only asks for this; self-reported LLM compliance is
    not a control, so this is checked the same way _missing_headings()
    checks SRS/HLD section compliance before trusting a response.
    """
    return bool(re.search(r"```mermaid\b.*?```", text, re.DOTALL))


SOURCE_FILE_EXCLUDED_DIRS = frozenset({"docs", "uml", "drawio", "tests", "__pycache__", ".git", "node_modules"})


def list_source_files(workdir: Path) -> list[str]:
    """List generated source files in workdir, excluding SDLC/tooling directories.

    Excludes docs/, uml/, drawio/, tests/, __pycache__/, .git/, node_modules/
    so the traceability persona is never fed its own prior output (SRS.md,
    HLD.md, uml/*.md) as if it were application source code.
    """
    files = []
    for path in sorted(workdir.rglob("*")):
        if not path.is_file():
            continue
        if any(part in SOURCE_FILE_EXCLUDED_DIRS for part in path.relative_to(workdir).parts):
            continue
        files.append(str(path.relative_to(workdir)))
    return files


def uml_dir_for(workdir: Path) -> Path:
    """Return the conventional uml/ directory for a workdir."""
    return workdir / "uml"


def diagram_path_for(workdir: Path, diagram_type: str) -> Path:
    """Return the conventional path for one diagram type's .md file."""
    return uml_dir_for(workdir) / f"{diagram_type}_diagram.md"


def generate_docs(
    srs: str,
    hld: str,
    workdir: Path,
    router: Router,
    client: LLMClient,
    on_event: OnEvent = noop_event,
) -> dict[str, str]:
    """Generate the 4 in-scope Mermaid diagrams and write them to workdir/uml/.

    Spawns all 4 diagram personas as genuinely separate OS processes
    simultaneously (see module docstring for what that does and doesn't
    buy), then awaits each individually so one failed/malformed diagram
    never discards the other 3 already-successful ones -- required by
    rules/45-uml-diagram-lifecycle.md's mandatory per-diagram failure
    isolation ("diagram generation failures MUST NOT block the pipeline").

    Args:
        srs: The approved SRS.md content.
        hld: The approved HLD.md content.
        workdir: Project directory; diagrams are written under its uml/ tree.
        router: Resolves model roles to live candidates.
        client: The multi-provider LLM client to call through.
        on_event: Progress event sink (see engine/calling.py).

    Returns:
        {diagram_type: content} for only the diagrams that succeeded.
        uml/*.md files are unconditionally overwritten on each call, per
        rule 45 Section 2 ("do NOT version diagram files").
    """
    on_event({"type": "docs_generation_started", "diagram_types": list(DIAGRAM_PERSONAS)})
    uml_dir = uml_dir_for(workdir)
    results: dict[str, str] = {}
    ast_resolved_types: set[str] = set()

    # AST-first pass: a synchronous pre-step in this (coordinator) process,
    # not inside any multiprocessing child -- call_mcp_tools() never touches
    # AgentCoordinator/RemoteLLM. Fail-open per type: any failure here just
    # leaves that type out of ast_resolved_types, falling through to the
    # existing LLM persona path below exactly as if MCP were never called.
    uml_server = MCP_SERVERS.get("uml-diagram")
    if uml_server is not None and uml_server.is_file():
        ast_calls = [
            (f"generate_{diagram_type}_diagram", {"project_path": str(workdir), "output_dir": str(uml_dir)})
            for diagram_type in AST_DIAGRAM_TYPES
        ]
        ast_results = call_mcp_tools(uml_server, ast_calls)
        for diagram_type, mcp_result in zip(AST_DIAGRAM_TYPES, ast_results):
            if not mcp_result.ok:
                continue
            output_file = mcp_result.data.get("output_file")
            if not output_file:
                continue
            try:
                content = Path(output_file).read_text(encoding="utf-8")
            except OSError:
                continue
            if not _has_mermaid_fence(content):
                continue

            uml_dir.mkdir(parents=True, exist_ok=True)
            diagram_path_for(workdir, diagram_type).write_text(DIAGRAM_FRONTMATTER + content, encoding="utf-8")
            results[diagram_type] = content
            ast_resolved_types.add(diagram_type)
            on_event({"type": "diagram_source", "diagram_type": diagram_type, "source": "ast"})
            on_event({"type": "diagram_generated", "diagram_type": diagram_type})

    # LLM path: unchanged eager-spawn-all/join-all/per-item-try-except
    # failure-isolation loop from Milestone 2, just filtered to the types
    # the AST pass above didn't already resolve.
    llm_diagram_types = [dt for dt in DIAGRAM_PERSONAS if dt not in ast_resolved_types]
    coordinator = AgentCoordinator(router, client, on_event=on_event)
    try:
        spawned = [
            (diagram_type, *coordinator.spawn_agent(_persona_generate_diagram, (diagram_type, srs, hld)))
            for diagram_type in llm_diagram_types
        ]
        for _diagram_type, process, _agent_id in spawned:
            process.join()

        for diagram_type, _process, agent_id in spawned:
            try:
                content = coordinator.await_result(agent_id)
                if not _has_mermaid_fence(content):
                    raise ValueError("response did not contain a valid mermaid fence")
            except (RuntimeError, ValueError) as exc:
                on_event({"type": "diagram_generation_failed", "diagram_type": diagram_type, "reason": str(exc)})
                continue

            uml_dir.mkdir(parents=True, exist_ok=True)
            diagram_path_for(workdir, diagram_type).write_text(DIAGRAM_FRONTMATTER + content, encoding="utf-8")
            results[diagram_type] = content
            on_event({"type": "diagram_source", "diagram_type": diagram_type, "source": "llm"})
            on_event({"type": "diagram_generated", "diagram_type": diagram_type})
    finally:
        coordinator.stop()

    return results


def generate_traceability(
    srs: str,
    file_list: list[str],
    workdir: Path,
    router: Router,
    client: LLMClient,
    on_event: OnEvent = noop_event,
) -> str:
    """Append a Traceability Matrix section to SRS.md, mapping FR/NFR to files.

    Owns its own AgentCoordinator (scoped independently of generate_docs()'s,
    matching sdlc.py's one-coordinator-per-generate-function convention),
    since this is called as a distinct step after generate_docs() has
    already stopped its own.

    Args:
        srs: The approved SRS.md content (without a Traceability Matrix yet).
        file_list: Relative paths of generated source files -- paths only,
            never file contents, sent to the persona.
        workdir: Project directory; SRS.md is read from/written to its docs/ tree.
        router: Resolves model roles to live candidates.
        client: The multi-provider LLM client to call through.
        on_event: Progress event sink (see engine/calling.py).

    Returns:
        The full SRS.md content including the new trailing section.

    Raises:
        GenerationError: If SRS.md already has a Traceability Matrix section.
    """
    if TRACEABILITY_HEADING in srs:
        raise GenerationError(
            "Traceability Matrix already present in SRS.md -- delete that section manually to regenerate it."
        )

    coordinator = AgentCoordinator(router, client, on_event=on_event)
    try:
        process, agent_id = coordinator.spawn_agent(_persona_generate_traceability, (srs, file_list))
        process.join()
        table = coordinator.await_result(agent_id)
    finally:
        coordinator.stop()

    on_event({"type": "traceability_generated"})
    srs_with_traceability = f"{srs}\n\n{TRACEABILITY_HEADING}\n\n{table}\n"

    srs_path_for(workdir).write_text(srs_with_traceability, encoding="utf-8")
    return srs_with_traceability
